[backdrop]
enabled = true

[bar]
order = [ "normal" ]

    [bar.normal]
    background_opacity = 0.59999998658895493
    capsule_thickness = 0.75999998673796654
    center = [ "clock", "line", "date", "line", "weather" ]
    concave_edge_corners = false
    end = [
        "group:g1",
        "line",
        "cpu",
        "ram",
        "line",
        "battery",
        "network",
        "bluetooth",
        "volume",
        "brightness",
        "group:g2",
        "line",
        "notifications"
    ]
    font_family = "Google Sans Code"
    font_weight = 500
    margin_ends = 0
    padding = 16
    panel_overlap = 2
    position = "top"
    radius = 0
    radius_bottom_left = 0
    radius_bottom_right = 0
    scale = 0.85000000521540642
    start = [ "control-center", "taskbar", "line", "layout", "line", "privacy" ]
    thickness = 30
    widget_spacing = 8

        [[bar.normal.capsule_group]]
        accordion = true
        accordion_direction = "start"
        enabled = true
        fill = "surface_variant"
        id = "g1"
        members = [ "tray", "notes_2", "clipboard", "wallpaper", "screenshot" ]
        opacity = 0.0
        padding = 6.0

        [[bar.normal.capsule_group]]
        accordion = false
        accordion_direction = "end"
        enabled = true
        fill = "surface_variant"
        id = "g2"
        members = [ "headphonesymbol", "headphone_battery" ]
        opacity = 0.0
        padding = 6.0

[battery.device."/org/freedesktop/UPower/devices/headset_dev_80_99_E7_8E_80_47"]
warning_threshold = 20

[desktop_widgets]
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000001]
    box_height = 160.0
    box_width = 304.0
    cx = 1840.0
    cy = 120.0
    output = "DP-1"
    rotation = 0.0
    type = "clock"

        [desktop_widgets.widget.desktop-widget-0000000000000001.settings]
        background = false
        color = "on_surface_variant"
        font_family = "TeX Gyre Termes"
        format = "{:%A}"

    [desktop_widgets.widget.desktop-widget-0000000000000002]
    box_height = 48.0
    box_width = 224.0
    cx = 1840.0
    cy = 184.0
    output = "DP-1"
    rotation = 0.0
    type = "clock"

        [desktop_widgets.widget.desktop-widget-0000000000000002.settings]
        background = false
        font_family = "TeX Gyre Schola"
        format = "{:%d %b | %H:%M}"

[dock]
background_opacity = 0.59999998658895493
border_width = 1.0
cross_axis_padding = 0
enabled = true
icon_size = 36
item_spacing = 4
launcher_position = "start"
layer = "overlay"
main_axis_padding = 8
margin_edge = 8
pinned = [
    "zen-beta",
    "com.mitchellh.ghostty",
    "dev.zed.Zed",
    "org.gnome.Nautilus",
    "org.gnome.Calculator",
    "org.gnome.SystemMonitor",
    "bitwarden",
    "org.gnome.Papers",
    "obsidian",
    "com.moonlight_stream.Moonlight",
    "steam",
    "vesktop"
]
reserve_space = false
show_dots = true
show_instance_count = false
smart_auto_hide = true

[location]
auto_locate = true

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [ "lockscreen-login-box@WL-1", "lockscreen-login-box@DP-1", "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 196.0
    box_width = 720.0
    cx = 1280.0
    cy = 1152.0
    output = "DP-1"
    placement_height = 1152.0
    placement_width = 2048.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@WL-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 632.0
    cy = 1208.0
    output = "WL-1"
    placement_height = 0.0
    placement_width = 0.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@WL-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 720.0
    cx = 768.0
    cy = 841.0
    output = "eDP-1"
    placement_height = 960.0
    placement_width = 1536.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[osd.kinds]
media = false

[plugin_settings."local/umbriel-layout"]
picker_open_near_click = false

[plugin_settings."noctalia/notes"]
notes_dir = "/home/mischa/Documents/ObsidianVault"

[plugins]
auto_update = "all"
enabled = [ "noctalia/notes", "noctalia/timer", "noctalia/example", "local/umbriel-layout" ]

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/official-plugins"
    name = "official"

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/community-plugins"
    name = "community"

    [[plugins.source]]
    kind = "path"
    location = "/home/mischa/nixos-dotfiles/config/noctalia/plugins"
    name = "my-plugins"

[shell]
app_icon_color = "primary"
avatar_path = "/home/mischa/nixos-dotfiles/assets/images/NixOS.png"
font_family = "JetBrainsMono NF"
polkit_agent = true

    [shell.launcher]
    categories = false

    [shell.panel]
    transparency_mode = "soft"
    wallpaper_placement = "centered"

    [shell.screenshot]
    directory = "/home/mischa/Pictures/Screenshots"

[theme]
builtin = "Catppuccin"
community_palette = "Peche"
custom_palette = "lofi-cat-ts"
mode = "dark"
source = "community"
wallpaper_scheme = "m3-tonal-spot"

    [theme.templates]
    builtin_ids = [ "btop", "gtk3", "gtk4", "ghostty", "hyprland", "kcolorscheme", "kitty", "niri", "umbriel" ]
    community_ids = [ "opencode", "discord", "vscode" ]

[wallpaper]
directory = "/home/mischa/nixos-dotfiles/assets/Wallpapers"

    [wallpaper.default]
    path = "/home/mischa/nixos-dotfiles/assets/Wallpapers/5825746.jpg"

    [wallpaper.last]
    path = "/home/mischa/nixos-dotfiles/assets/Wallpapers/5825746.jpg"

    [wallpaper.monitors.DP-1]
    path = "/home/mischa/nixos-dotfiles/assets/Wallpapers/5825746.jpg"

    [wallpaper.monitors.eDP-1]
    path = "/home/mischa/nixos-dotfiles/assets/Wallpapers/5825746.jpg"

    [[wallpaper.favorite]]
    palette_source = "wallpaper"
    path = "/home/mischa/nixos-dotfiles/assets/Wallpapers/wallhaven-jx9kxp.jpg"
    theme_mode = "dark"
    wallpaper_scheme = "m3-tonal-spot"

    [[wallpaper.favorite]]
    palette_source = "wallpaper"
    path = "/home/mischa/nixos-dotfiles/assets/Wallpapers/moonrise-rolling-3840x2160-25877.jpg"
    theme_mode = "dark"
    wallpaper_scheme = "m3-content"

    [[wallpaper.favorite]]
    community_palette = "Peche"
    palette_source = "community"
    path = "/home/mischa/nixos-dotfiles/assets/Wallpapers/5825746.jpg"
    theme_mode = "dark"

    [[wallpaper.favorite]]
    community_palette = "Kanagawa Dragon"
    palette_source = "community"
    path = "/home/mischa/nixos-dotfiles/assets/Wallpapers/pexels-sheep-556180-1846422.jpg"
    theme_mode = "dark"

[widget.battery]
hide_when_plugged = true

[widget.brightness]
show_label = false

[widget.clock]
capsule_fill = "surface"
format = "{:%H:%M}"

[widget.control-center]
custom_image = "/home/mischa/nixos-dotfiles/assets/images/NixOS.png"
custom_image_colorize = true
glyph = "snowflake"

[widget.cpu]
visualization = "none"

[widget.date]
format = "{:%a, %d.%m}"
scale = 1.0

[widget.headphone_battery]
device = "/org/freedesktop/UPower/devices/headset_dev_80_99_E7_8E_80_47"
display_mode = "none"
type = "battery"

[widget.headphonesymbol]
glyph = "bluetooth-device-headphones"
interactive = false
type = "custom_button"

[widget.layout]
type = "local/umbriel-layout:layout"

[widget.line]
glyph = "minus-vertical"
interactive = false
type = "custom_button"

[widget.network]
show_label = false

[widget.notes]
type = "noctalia/notes:notes"

[widget.notes_2]
type = "noctalia/notes:notes"

[widget.privacy]
active_color = "tertiary"
inactive_color = "on_surface"

[widget.ram]
visualization = "none"

[widget.taskbar]
capsule_radius = 8
group_by_workspace = true
hide_empty_workspaces = true
icon_scale = 1.5000000000000002
inactive_opacity = 0.80000000000000004
minimal = true
scale = 1.0
show_active_indicator = false
show_window_title = false
workspace_label_placement = "inside"

[widget.tray]
drawer = true

[widget.volume]
show_label = false

[widget.weather]
show_condition = false

[widget.workspaces]
active_pill_size = 1.1499999999999999
capsule_radius = 3
inactive_pill_size = 1.1499999999999999
scale = 1.5
style = "focus_hint"
