color0 #454559
color1 #ffb4ab
color2 #79d1ff
color3 #8fcff3
color4 #bfc1ff
color5 #79d1ff
color6 #8fcff3
color7 #e3e1ef
color8 #8f8fa6
color9 #ffb4ab
color10 #79d1ff
color11 #8fcff3
color12 #bfc1ff
color13 #79d1ff
color14 #8fcff3
color15 #e3e1ef

cursor                #e3e1ef
cursor_text_color     #12131c
background            #12131c
foreground            #e3e1ef
selection_foreground  #c5c4dd
selection_background  #454559
active_border_color   #79d1ff
inactive_border_color #454559
url_color             #79d1ff

active_tab_foreground   #003549
active_tab_background   #79d1ff
inactive_tab_foreground #c5c4dd
inactive_tab_background #454559
cursor_trail_color      #c5c4dd
