color0 #45464e
color1 #ffb4ab
color2 #b7c5f7
color3 #c1c6dc
color4 #ebb6e0
color5 #b7c5f7
color6 #c1c6dc
color7 #e4e2e6
color8 #8f9099
color9 #ffb4ab
color10 #b7c5f7
color11 #c1c6dc
color12 #ebb6e0
color13 #b7c5f7
color14 #c1c6dc
color15 #e4e2e6

cursor                #e4e2e6
cursor_text_color     #131316
background            #131316
foreground            #e4e2e6
selection_foreground  #c6c6d0
selection_background  #45464e
active_border_color   #b7c5f7
inactive_border_color #45464e
url_color             #b7c5f7

active_tab_foreground   #202e58
active_tab_background   #b7c5f7
inactive_tab_foreground #c6c6d0
inactive_tab_background #45464e
cursor_trail_color      #c6c6d0
