color0 #3f4759
color1 #ffb4ab
color2 #53d7f2
color3 #84d2e5
color4 #acc7ff
color5 #53d7f2
color6 #84d2e5
color7 #dfe2ef
color8 #8991a5
color9 #ffb4ab
color10 #53d7f2
color11 #84d2e5
color12 #acc7ff
color13 #53d7f2
color14 #84d2e5
color15 #dfe2ef

cursor                #dfe2ef
cursor_text_color     #0f131c
background            #0f131c
foreground            #dfe2ef
selection_foreground  #bec6dc
selection_background  #3f4759
active_border_color   #53d7f2
inactive_border_color #3f4759
url_color             #53d7f2

active_tab_foreground   #00363f
active_tab_background   #53d7f2
inactive_tab_foreground #bec6dc
inactive_tab_background #3f4759
cursor_trail_color      #bec6dc
