color0 #080b12
color1 #ef748b
color2 #95d067
color3 #d9b06c
color4 #76a9fa
color5 #b49cf8
color6 #73d7ff
color7 #a9b1d6
color8 #4d577f
color9 #f48aa0
color10 #a7db7d
color11 #e3bc84
color12 #8ab6ff
color13 #c5b0fb
color14 #8ae2ff
color15 #c0caf5

cursor                #c0caf5
cursor_text_color     #080b12
background            #080b12
foreground            #c0caf5
selection_foreground  #c0caf5
selection_background  #243250
active_border_color   #76a9fa
inactive_border_color #131a2a
url_color             #76a9fa

active_tab_foreground   #080b12
active_tab_background   #76a9fa
inactive_tab_foreground #a9b1d6
inactive_tab_background #131a2a
cursor_trail_color      #a9b1d6
